import { c } from "../ui.ts";
import { CLI_VERSION } from "../version.ts";

const GENERAL_HELP = `
${c.bold("devswitch")} ${c.gray("v" + CLI_VERSION)} — manage multiple Git profiles & SSH keys

${c.bold("USAGE")}
  devswitch <command> [options]

${c.bold("COMMANDS")}
  ${c.cyan("list")}                     List all saved profiles            ${c.gray("(alias: ls)")}
  ${c.cyan("use")} <profile>            Switch to a profile                ${c.gray("(alias: switch)")}
  ${c.cyan("current")}                  Show the currently active profile  ${c.gray("(alias: whoami)")}
  ${c.cyan("add")}                      Create a new profile               ${c.gray("(alias: create)")}
  ${c.cyan("remove")} <profile>         Delete a profile                   ${c.gray("(alias: rm, delete)")}
  ${c.cyan("show")} <profile>           Show full details of a profile     ${c.gray("(alias: view, info)")}
  ${c.cyan("sync")}                     Import unmanaged SSH keys as profiles
  ${c.cyan("test")} <profile>           Test the SSH connection for a profile
  ${c.cyan("pubkey")} <profile>         Print & copy a profile's public key ${c.gray("(alias: key, sshkey, pub)")}
  ${c.cyan("clone")} <url> [dir]        Clone a repo using a profile's identity
  ${c.cyan("logs")}                     Show recent activity log
  ${c.cyan("path")}                     Show the shared data directory path
  ${c.cyan("doctor")}                   Diagnose environment & data store
  ${c.cyan("help")} [command]           Show help (this screen)
  ${c.cyan("version")}                  Print the CLI version              ${c.gray("(alias: -v)")}

${c.bold("GLOBAL OPTIONS")}
  -h, --help               Show help for a command
  -v, --version            Print version
  --json                   Output machine-readable JSON where supported
  --no-color               Disable colored output (or set NO_COLOR=1)

${c.bold("EXAMPLES")}
  devswitch list
  devswitch use work
  devswitch add --name "Work" --email me@work.com --username me --provider github --generate
  devswitch sync
  devswitch clone git@github.com:acme/app.git ~/code --profile work

${c.gray("Profiles are shared with the DevSwitch desktop app — changes here appear there and vice versa.")}
${c.gray("Run 'devswitch help <command>' for details on a specific command.")}
`;

const COMMAND_HELP: Record<string, string> = {
  list: `${c.bold("devswitch list")} — list all saved profiles

USAGE
  devswitch list [--json]

OPTIONS
  --json     Print profiles as JSON

Shows each profile's name, username, email, provider, SSH key type, and whether
its SSH host alias is configured.`,

  use: `${c.bold("devswitch use")} <profile> — switch to a profile

USAGE
  devswitch use <profile> [options]

ARGUMENTS
  <profile>            Profile name, username, email, or id (partial match ok)

OPTIONS
  --no-global-git      Do NOT change the global git user.name / user.email
  --json               Print result as JSON

WHAT IT DOES
  • Ensures the profile's Host alias exists in ~/.ssh/config
  • Loads the profile's key into ssh-agent
  • Sets global git user.name / user.email (unless --no-global-git)
  • Prints the clone URL format to use for this profile`,

  add: `${c.bold("devswitch add")} — create a new profile

USAGE
  devswitch add [options]

OPTIONS
  --name <name>             Friendly profile name
  --email <email>           Git email
  --username <username>     Provider username
  --provider <provider>     github | gitlab | bitbucket | azure | other  (default: github)
  --default                 Use the default key (~/.ssh/id_ed25519 or id_rsa)
  --generate                Generate a new SSH key
  --algorithm <algo>        ed25519 | rsa   (with --generate, default: ed25519)
  --key-name <name>         Filename for the generated key (with --generate)
  --passphrase <pass>       Passphrase for the generated key (optional)
  --existing <path>         Use an existing private key at <path>
  --avatar <emoji>          Avatar emoji (default 👤)
  --color <hex>             Accent color (default #3b82f6)

If required values are missing, you'll be prompted interactively.`,

  remove: `${c.bold("devswitch remove")} <profile> — delete a profile

USAGE
  devswitch remove <profile> [--yes] [--json]

ARGUMENTS
  <profile>     Profile name, username, email, or id

OPTIONS
  -y, --yes     Skip the confirmation prompt

Removes the profile's ~/.ssh/config entry. Keys generated by DevSwitch are also
deleted from disk; imported/default keys are left untouched.`,

  show: `${c.bold("devswitch show")} <profile> — show full profile details

USAGE
  devswitch show <profile> [--json]`,

  sync: `${c.bold("devswitch sync")} — import unmanaged SSH keys as profiles

USAGE
  devswitch sync [--json]

Scans ~/.ssh and ~/.ssh/config, then creates profiles for any keys not already
managed by DevSwitch. Existing profiles are never duplicated.`,

  test: `${c.bold("devswitch test")} <profile> — test the SSH connection

USAGE
  devswitch test <profile> [--json]

Runs 'ssh -T' against the profile's provider host alias using its key.`,

  clone: `${c.bold("devswitch clone")} <url> [dir] — clone a repo with a profile's identity

USAGE
  devswitch clone <repo-url> [destination-dir] --profile <profile>

ARGUMENTS
  <repo-url>            HTTPS or SSH repository URL
  [destination-dir]    Folder to clone into (default: current directory)

OPTIONS
  --profile <profile>  Profile to use (required)

Rewrites the URL to use the profile's SSH host alias and sets the repo's local
git user.name / user.email.`,

  pubkey: `${c.bold("devswitch pubkey")} <profile> — print & copy a profile's SSH public key

USAGE
  devswitch pubkey <profile>

ALIASES
  key, sshkey, ssh-key, publickey, pub

Copies the key to the clipboard automatically.`,
  logs: `${c.bold("devswitch logs")} — show recent activity\n\nUSAGE\n  devswitch logs [--limit <n>] [--json]`,
  path: `${c.bold("devswitch path")} — print the shared data directory path`,
  doctor: `${c.bold("devswitch doctor")} — diagnose environment and data store`,
  current: `${c.bold("devswitch current")} — show the active profile (based on global git config)`,
};

export function printHelp(command?: string): void {
  if (command && COMMAND_HELP[command]) {
    console.log("\n" + COMMAND_HELP[command] + "\n");
    return;
  }
  console.log(GENERAL_HELP);
}
